### ISSUE TITLE
urlselect not showing anything

### ISSUE THREAD

**Issue by drselump14** [tomoe-mami/weechat-scripts#5]
Hello, I'm very interested on your urlselect plugin. I installed the script and input /urlselect, but nothing happened? any help would be appreciated

**Comment by weechatter** [comment]
first of all, its a script not a plugin. A plugin is something different in weechat.

Did you try /help urlselect ?

**Comment by tomoe-mami** [comment]
Does the line that contain URL your own message? Default setting for urlselect is to only collects URLs in messages from other people. You can change it with option `plugins.var.lua.urlselect.tags`. Its default value is `notify_message` (other people's message in channel), `notify_private` (private message), and `notify_highlight` (highlight).  You can check the tags of message using command `/debug tags`. If you're unsure, you can set it to empty string:

    /set plugins.var.lua.urlselect.tags ""

This should collect URLs in any line in a buffer like quit messages, topic changes, kick reasons, etc.

If it still doesn't show anything after you set the option to empty, please paste (or screenshot) the example of lines that are not collected by the script.

**Comment by drselump14** [comment]
@weechatter sorry for using wrong term ... I did try /help urlselect
@tomoe-mami Thanks for the help.With the `/set plugins.var.lua.urlselect.tags = "" ` , it works as expected .. thanks a lot
